### ISSUE TITLE
[URGENT] Standardize Proceedings Citation.

### ISSUE THREAD

**Issue by Itaborala** [isqcmc/isqcmc.github.io#11]
At some point this year I had to cite the ISQCMC Berlin proceedings as a whole, for a book chapter. This is what I ended up using in my case, in APA Format:
Hamido, O. C. and Itaboraı́, P. V. (eds.) (2023b). Proceedings of the 2nd Inter-
national Symposium on Quantum Computing and Musical Creativity (Zen-
odo), https://isqcmc.github.io/Proceedings, [Conference proceedings].

I've now exchanged some emails with another ISQCMC author, and they refered to the proceedings, while citing their paper like so:

Authors, Title. arxivDOI. In: Proceedings of the 2nd International Symposium on Quantum Computing and Musical Creativity 2023, K. Jansen (ed) (2023), PDF/DOI: 10.5281/zenodo.XXXXX

This means we need to update this information urgently, so we make sure the citations are correct and uniform - and easily accessible.

**TODO:**
- [x] edit the about page of zenodo
- [x] add reference of entire proceedings

**Comment by omarcostahamido** [comment]
Hi. Thanks for creating an issue for this :)

I confess I thought that if people refer to their own work, or an individual work, they wouldn't need to add our names to the reference... And we made that pretty quick and easy with the buttons on the website: https://isqcmc.github.io/Proceedings#2023---isqcmc-berlin---paper-proceedings
Now, you bring up a good point: what if they want to cite the entire proceedings as a whole? Well, in that case, it is easy to know who put things together [here](https://zenodo.org/communities/isqcmc_proceedings/about) and on the footer of the [website](https://isqcmc.github.io/).

So, yes. Let's do that. Add a reference at the top of [this page](https://isqcmc.github.io/Proceedings#2023---isqcmc-berlin---paper-proceedings) and on the [about page](https://zenodo.org/communities/isqcmc_proceedings/about) of zenodo as well.

It could be like you wrote it.
```
Hamido, O. C. and Itaboraı́, P. V. (eds.) (2023b). Proceedings of the 2nd International Symposium on Quantum Computing and Musical Creativity (Zenodo), https://isqcmc.github.io/Proceedings, [Conference proceedings].
```
But why 2023**b**?

Let's do the multiple references, yes?
opening a branch

**Comment by Itaborala** [comment]
Thanks a lot @omarcostahamido for working so quickly on this!

The (2023b) is just because I also cited our previous OSCQasm paper on the same chapter (2023a), which is how APA automatically handles two publications of the same authors on the same year. In the website we probably shouldn't need the 'b'....

**Comment by omarcostahamido** [comment]
🪿
