### ISSUE TITLE
add bibtex to all paper entries!

### ISSUE THREAD

**Issue by isqcmc** [isqcmc/isqcmc.github.io#4]
- [x] @omarcostahamido will create the copy bibtex button
- [x] @Itaborala will generate all the bibtex

**Comment by Itaborala** [comment]
@inproceedings{ISQCMC_itaborai,
 address = {Berlin},
 author = {Itaboraí, Paulo Vitor and Schwägerl, Tim and Yáñez, María Aguado and Crippa, Arianna and Jansen, Karl and Miranda, Eduardo Reck and Thomas, Peter},
 booktitle = {2nd International Symposium on Quantum Computing and Musical Creativity (ISQCMC Berlin)},
 doi = {10.5281/zenodo.10206731},
 day = {05},
 month = {October},
 presentation-video = {https://youtu.be/},
 title = {Variational Quantum Harmonizer: Generating Chord Progressions and Other Sonification Methods with the VQE Algorithm},
 url = {https://doi.org/10.5281/zenodo.10206731},
 year = {2023}
}

**Comment by Itaborala** [comment]
Test bibtex above
