### ISSUE TITLE
Add ISQCMC picture on website

### ISSUE THREAD

**Issue by Itaborala** [isqcmc/isqcmc.github.io#8]
When convenient, please add this figure with the page header:

![Screenshot 2023-11-23 162530](https://github.com/isqcmc/isqcmc.github.io/assets/28213905/cd8d7b5a-8fcf-40ea-a305-6f0ed5aed894)

**Comment by omarcostahamido** [comment]
_ooof!_ how is it possible that we missed this?
ok i can take this one.
